apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: orion
  name: orion
spec:
  path: orion
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orion
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: orion
    spec:
      containers:
        - args:
            - -corsOrigin
            - __ALL
            - -dbhost
            - mongo-db
            - -logLevel
            - DEBUG
            - -forwarding
          image: 'fiware/orion-ld:'
          livenessProbe:
            exec:
              command:
                - curl --fail -s http://orion:/version || exit 1
            periodSeconds: 5
          name: fiware-orion
          ports:
            - containerPort: 1026
          resources: {}
      hostname: orion
      restartPolicy: Always
status: {}
