apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orion
  name: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orion
    spec:
      containers:
      - command: ["orionld"]
        args: ["-fg", "-multiservice", "-ngsiv1Autocast", "-dbhost", "mongodb",
               "-logLevel", "DEBUG"]
          #  - -corsOrigin
          # - __ALL
          # - -dbhost
          # - mongo-db
          #- -logLevel
          # DEBUG
          #-forwarding
          
          image: "fiware/orion-ld:0.8.0"
#          livenessProbe:
#            exec:
#              command:
#                - curl --fail -s http://orion:/version || exit 1
#            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: fiware-orion
          ports:
            - containerPort: 1026
          resources: {}
      hostname: orion
      restartPolicy: Always
status: {}
