apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orion
  name: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - command: ["orionld"]
        args: ["-fg", "-multiservice", "-ngsiv1Autocast", "-dbhost", "mongo-db",
               "-logLevel", "DEBUG"]
        image: "fiware/orion-ld:0.8.0"
        imagePullPolicy: IfNotPresent
        name: orion
        ports:
        - containerPort: 1026
        
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  creationTimestamp: null
#  labels:
#    app: orion
#  name: orion
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: orion
#  strategy: {}
#  template:
#    metadata:
#      creationTimestamp: null
#      labels:
#        app: orion
#    spec:
#      containers:
#        - args:
#            - -corsOrigin
#            - __ALL
#            - -dbhost
#            - mongo-db
#            - -logLevel
#            - DEBUG
#            - -forwarding
#            
#          image: 'fiware/orion-ld:0.8.0'
#          imagePullPolicy: IfNotPresent
          
  #          livenessProbe:
  #            exec:
  #              command:
  #                - curl --fail -s http://orion:/version || exit 1
  #            periodSeconds: 5
    
#          name: orion
#          ports:
#            - containerPort: 1026
#         resources: {}
#        hostname: orion
#        restartPolicy: Always
#status: {}
