apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orion
  name: orion
spec:
  type: NodePort
  ports:
    - name: "1026"
      port: 1026
      targetPort: 1026
 #    nodePort: 30000 # Is necessary to specify a port greater than or equal to 30000.
  selector:
    app: orion
status:
  loadBalancer: {}
