apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: orion
  name: orion
spec:
  ports:
    - name: "1026"
      port: 1026
      targetPort: 1026
  selector:
    io.kompose.service: orion
status:
  loadBalancer: {}
