apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shopfloorRoughnator
  name: shopfloorRoughnator
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 3000
  selector:
    app: grafana
status:
  loadBalancer: {}
