apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: roughnator
  name: roughnator
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 3000
  selector:
    app: roughnator
status:
  loadBalancer: {}
