apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argocd
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  path: pgadmin
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
