apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  path: pgadmin
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  ports:
    - name: "8200"
      port: 8200
      targetPort: 80
  selector:
    io.kompose.service: pgadmin
status:
  loadBalancer: {}
