apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: timescale
  name: timescale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: timescale
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: '*'
          image: timescale/timescaledb-postgis:1.7.5-pg12
          name: postgre-timescale
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: timescale
      restartPolicy: Always
      volumes:
        - name: timescale
          persistentVolumeClaim:
            claimName: timescale
status: {}
