apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: timescale
  name: timescale
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: timescale
status:
  loadBalancer: {}
