apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: quantumleap-db-setup
  name: quantumleap-db-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quantumleap-db-setup
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: quantumleap-db-setup
    spec:
      containers:
        - env:
            - name: PG_HOST
              value: 172.17.0.14 #timescale
            - name: PG_PASS
              value: '*'
            - name: QL_DB_INIT_DIR
              value: /ql-db-init
            - name: QL_DB_PASS
              value: '*'
          image: orchestracities/quantumleap-pg-init
          name: quantumleap-db-setup
          resources: {}
      restartPolicy: Always
status: {}
