apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: quantumleap
  name: quantumleap
spec:
  ports:
    - name: "8668"
      port: 8668
      targetPort: 8668
  selector:
    app: quantumleap
status:
  loadBalancer: {}
