apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: quantumleap
  name: quantumleap
spec:
  ports:
    - name: "8668"
      port: 8668
      targetPort: 8668
  selector:
    io.kompose.service: quantumleap
status:
  loadBalancer: {}
