apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quantumleap-db-setup
  name: quantumleap-db-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumleap-db-setup
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quantumleap-db-setup
    spec:
      containers:
        - env:
            - name: PG_HOST
              value: timescale
            - name: PG_PASS
              value: '*'
            - name: QL_DB_INIT_DIR
              value: /ql-db-init
            - name: QL_DB_PASS
              value: '*'
          image: orchestracities/quantumleap-pg-init
          name: quantumleap-db-setup
          resources: {}
      restartPolicy: Always
status: {}
