apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      protocol: TCP
      targetPort: 27017
#    - name: 27017-tcp
#      port: 27017
#      targetPort: 27017
  selector:
    app: mongodb
status:
  loadBalancer: {}
