apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
#    - name: 27017-tcp
#      port: 27017
#      targetPort: 27017
  selector:
    app: mongo-db
status:
  loadBalancer: {}
