apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo-db
status:
  loadBalancer: {}
