apiVersion: argoproj.io/v1alpha1
kind: Service
metadata:
  namespace: argocd
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  source:
    path: grafana
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
