apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "8200"
      port: 8200
      targetPort: 80
  selector:
    app: pgadmin
status:
  loadBalancer: {}
