apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reco
  name: reco
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    app: reco
status:
  loadBalancer: {}
