apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: reco
  name: reco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reco
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reco
    spec:
      containers:
        - env:
            - name: ORION_URL
              value: http://kitt4sme.collab-cloud.eu/orion
          image: reco
          imagePullPolicy: IfNotPresent
          name: reconfigurator
          ports:
            - containerPort: 8050
              hostPort: 8050
              protocol: TCP
          resources: {}
      hostname: reco
      restartPolicy: Always
status: {}
