apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: timescale
  name: timescale
spec:
  path: timescale
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: timescale
status:
  loadBalancer: {}
