apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ig
  name: ig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ig
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ig
    spec:
      containers:
        - image: ig
          imagePullPolicy: IfNotPresent
          name: insight-generator
          ports:
            - containerPort: 8010
          resources: {}
      hostname: insight-generator
      restartPolicy: Always
status: {}
