apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ig
  name: ig
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8010
    - name: 8010-tcp
      port: 8010
      targetPort: 8010
  selector:
    app: ig
status:
  loadBalancer: {}
