apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  path: redis
    repoURL: https://github.com/AntonioUzal-CSIC/Arquitectura.git
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:6.2.3
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
