apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: context-provider
  name: context-provider
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: 3000-tcp
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: context-provider
status:
  loadBalancer: {}
