apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aiqusda
  name: aiqusda-service
spec:
  selector:
    app.kubernetes.io/name: aiqusda
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  type: ClusterIP
