apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "aiqus-virtual-service"
spec:
  gateways:
    - "kitt4sme-gateway"
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /da
    - uri:
        prefix: /bl
    - uri:
        prefix: /sp
    route:
    - destination:
        host: aiqusda-service.default.svc.cluster.local
        port:
          number: 8000
  - match:
    - uri:
        prefix: /docs/
    - uri:
        prefix: /docs
    - uri:
        prefix: /openapi.json
    route:
    - destination:
        host: aiqusda-service.default.svc.cluster.local
        port:
          number: 8000

