apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ocbv
  name: ocbv
spec:
  selector:
    app.kubernetes.io/name: ocbv
  ports:
    - name: "http"
      port: 28001
      targetPort: 5000
  type: ClusterIP