apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "ocbv-virtual-service"
spec:
  gateways:
  - "kitt4sme-gateway"
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /ocbv/
    rewrite:
      uri: /
    route:
    - destination:
        host: ocbv.default.svc.cluster.local
        port:
          number: 28001
  - match:
    - uri:
        prefix: /static/
    route:
    - destination:
        host: ocbv.default.svc.cluster.local
        port:
          number: 28001
#
