apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
status:
  loadBalancer: {}
